# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "lasso"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Daniels"]
  s.date = "2012-10-13"
  s.description = "Identity herding with OAuth"
  s.email = "james@marginleft.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "lasso.gemspec",
    "lib/lasso.rb",
    "lib/lasso/controller/base.rb",
    "lib/lasso/controller/instance.rb",
    "lib/lasso/controller/settings.rb",
    "lib/lasso/model/base.rb",
    "lib/lasso/model/instance.rb",
    "lib/lasso/model/oauth_one.rb",
    "lib/lasso/model/oauth_two.rb",
    "lib/lasso/model/settings.rb",
    "spec/controllers.rb",
    "spec/db/database.yml",
    "spec/db/models.rb",
    "spec/db/schema.rb",
    "spec/db/test.sqlite3",
    "spec/lasso_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/jamesdaniels/lasso"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Identity herding with OAuth"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 1.2.9"])
      s.add_runtime_dependency(%q<oauth2>, ["~> 0.8.0"])
      s.add_runtime_dependency(%q<oauth>, ["~> 0.4.7"])
    else
      s.add_dependency(%q<rspec>, ["~> 1.2.9"])
      s.add_dependency(%q<oauth2>, ["~> 0.8.0"])
      s.add_dependency(%q<oauth>, ["~> 0.4.7"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 1.2.9"])
    s.add_dependency(%q<oauth2>, ["~> 0.8.0"])
    s.add_dependency(%q<oauth>, ["~> 0.4.7"])
  end
end

